name: Validate Codecov Configuration

on:
  push:
    paths:
      - codecov.yaml
  pull_request:
    paths:
      - codecov.yaml

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Validate Codecov configuration
        run: |
          curl -X POST --data-binary @codecov.yaml https://codecov.io/validate
